# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
defaults: &defaults
  adapter: mysql
  encoding: utf8

development:
  username: user
  password: XXXXXXX
  database: mobdub_development
  host: localhost # development-db.c4swrdaqaphh.us-east-1.rds.amazonaws.com
  <<: *defaults

test:
  username: user
  password: XXXXXXX
  database: mobdub_test
  host: localhost
  <<: *defaults

production:
  username: user
  password: XXXXXXX
  database: mobdub_production
  host: production-db.c4swrdaqaphh.us-east-1.rds.amazonaws.com
  <<: *defaults
